//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaAppWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_VeterinariaEntities : DbContext
    {
        public BD_VeterinariaEntities()
            : base("name=BD_VeterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_mascota> tb_mascota { get; set; }
        public virtual DbSet<tb_producto> tb_producto { get; set; }
        public virtual DbSet<tb_proveedor> tb_proveedor { get; set; }
        public virtual DbSet<tb_Roles> tb_Roles { get; set; }
        public virtual DbSet<tb_servicios> tb_servicios { get; set; }
        public virtual DbSet<tb_tipo_documento> tb_tipo_documento { get; set; }
        public virtual DbSet<tb_tipo_mascota> tb_tipo_mascota { get; set; }
        public virtual DbSet<tb_tipo_producto> tb_tipo_producto { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
    
        public virtual int SP_EDITARUSUARIO(Nullable<int> iD_USU, Nullable<int> iD_ROL, string nOMBRE, string aPE_PAT, string aPE_MAT, Nullable<int> tIP_DOC, string nUM_DOC, string tELEF, string dIRECC, string cORREO, string pASSW, string eSTADO, string fOTO)
        {
            var iD_USUParameter = iD_USU.HasValue ?
                new ObjectParameter("ID_USU", iD_USU) :
                new ObjectParameter("ID_USU", typeof(int));
    
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPE_PATParameter = aPE_PAT != null ?
                new ObjectParameter("APE_PAT", aPE_PAT) :
                new ObjectParameter("APE_PAT", typeof(string));
    
            var aPE_MATParameter = aPE_MAT != null ?
                new ObjectParameter("APE_MAT", aPE_MAT) :
                new ObjectParameter("APE_MAT", typeof(string));
    
            var tIP_DOCParameter = tIP_DOC.HasValue ?
                new ObjectParameter("TIP_DOC", tIP_DOC) :
                new ObjectParameter("TIP_DOC", typeof(int));
    
            var nUM_DOCParameter = nUM_DOC != null ?
                new ObjectParameter("NUM_DOC", nUM_DOC) :
                new ObjectParameter("NUM_DOC", typeof(string));
    
            var tELEFParameter = tELEF != null ?
                new ObjectParameter("TELEF", tELEF) :
                new ObjectParameter("TELEF", typeof(string));
    
            var dIRECCParameter = dIRECC != null ?
                new ObjectParameter("DIRECC", dIRECC) :
                new ObjectParameter("DIRECC", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var pASSWParameter = pASSW != null ?
                new ObjectParameter("PASSW", pASSW) :
                new ObjectParameter("PASSW", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EDITARUSUARIO", iD_USUParameter, iD_ROLParameter, nOMBREParameter, aPE_PATParameter, aPE_MATParameter, tIP_DOCParameter, nUM_DOCParameter, tELEFParameter, dIRECCParameter, cORREOParameter, pASSWParameter, eSTADOParameter, fOTOParameter);
        }
    
        public virtual int SP_ELIMINARUSUARIO(Nullable<int> iD_USU)
        {
            var iD_USUParameter = iD_USU.HasValue ?
                new ObjectParameter("ID_USU", iD_USU) :
                new ObjectParameter("ID_USU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARUSUARIO", iD_USUParameter);
        }
    
        public virtual ObjectResult<SP_LISTARDOCUMENTOS_Result> SP_LISTARDOCUMENTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTARDOCUMENTOS_Result>("SP_LISTARDOCUMENTOS");
        }
    
        public virtual ObjectResult<SP_LISTARROLES_Result> SP_LISTARROLES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTARROLES_Result>("SP_LISTARROLES");
        }
    
        public virtual ObjectResult<SP_LISTARUSUARIOS_Result> SP_LISTARUSUARIOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTARUSUARIOS_Result>("SP_LISTARUSUARIOS");
        }
    
        public virtual ObjectResult<SP_LISTAUSUARIO_ORIGINAL_Result> SP_LISTAUSUARIO_ORIGINAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAUSUARIO_ORIGINAL_Result>("SP_LISTAUSUARIO_ORIGINAL");
        }
    
        public virtual ObjectResult<SP_LISTAUSUARIOXNOMBRE_Result> SP_LISTAUSUARIOXNOMBRE(string nOM)
        {
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAUSUARIOXNOMBRE_Result>("SP_LISTAUSUARIOXNOMBRE", nOMParameter);
        }
    
        public virtual int SP_NUEVOUSUARIO(Nullable<int> iD_USU, Nullable<int> iD_ROL, string nOMBRE, string aPE_PAT, string aPE_MAT, Nullable<int> tIP_DOC, string nUM_DOC, string tELEF, string dIRECC, string cORREO, string pASSW, string eSTADO, string fOTO)
        {
            var iD_USUParameter = iD_USU.HasValue ?
                new ObjectParameter("ID_USU", iD_USU) :
                new ObjectParameter("ID_USU", typeof(int));
    
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPE_PATParameter = aPE_PAT != null ?
                new ObjectParameter("APE_PAT", aPE_PAT) :
                new ObjectParameter("APE_PAT", typeof(string));
    
            var aPE_MATParameter = aPE_MAT != null ?
                new ObjectParameter("APE_MAT", aPE_MAT) :
                new ObjectParameter("APE_MAT", typeof(string));
    
            var tIP_DOCParameter = tIP_DOC.HasValue ?
                new ObjectParameter("TIP_DOC", tIP_DOC) :
                new ObjectParameter("TIP_DOC", typeof(int));
    
            var nUM_DOCParameter = nUM_DOC != null ?
                new ObjectParameter("NUM_DOC", nUM_DOC) :
                new ObjectParameter("NUM_DOC", typeof(string));
    
            var tELEFParameter = tELEF != null ?
                new ObjectParameter("TELEF", tELEF) :
                new ObjectParameter("TELEF", typeof(string));
    
            var dIRECCParameter = dIRECC != null ?
                new ObjectParameter("DIRECC", dIRECC) :
                new ObjectParameter("DIRECC", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var pASSWParameter = pASSW != null ?
                new ObjectParameter("PASSW", pASSW) :
                new ObjectParameter("PASSW", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NUEVOUSUARIO", iD_USUParameter, iD_ROLParameter, nOMBREParameter, aPE_PATParameter, aPE_MATParameter, tIP_DOCParameter, nUM_DOCParameter, tELEFParameter, dIRECCParameter, cORREOParameter, pASSWParameter, eSTADOParameter, fOTOParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_ULTIMOUSUARIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_ULTIMOUSUARIO");
        }
    }
}
