//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_mascota
    {
        public int id_mascota { get; set; }
        public string nombre { get; set; }
        public string raza { get; set; }
        public Nullable<int> edad { get; set; }
        public string color { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> talla { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_tipo_masc { get; set; }
        public string estado { get; set; }
        public string foto { get; set; }
    
        public virtual tb_tipo_mascota tb_tipo_mascota { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
