//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuario()
        {
            this.tb_mascota = new HashSet<tb_mascota>();
        }
    
        public int id_usuario { get; set; }
        public Nullable<int> id_rol { get; set; }
        public string nombre { get; set; }
        public string ap_paterno { get; set; }
        public string ap_materno { get; set; }
        public Nullable<int> id_tipo_doc { get; set; }
        public string Numero_doc { get; set; }
        public string celular { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public string Contrasenia { get; set; }
        public string estado { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_mascota> tb_mascota { get; set; }
        public virtual tb_Roles tb_Roles { get; set; }
        public virtual tb_tipo_documento tb_tipo_documento { get; set; }
    }
}
